// POST /api/chat — boucle agentique + streaming SSE — et GET /api/prompt-preview.
// TRANSPARENCE TOTALE : le payload envoyé au backend = system prompt du personnage
// + bloc mémoire (si actif) + historique + message user. RIEN d'autre n'est injecté.
// buildPayload est LA source unique, partagée avec /api/prompt-preview.
import { Router } from 'express'
import type { Request, Response } from 'express'
import { loadSettings, workingWindow } from '../config'
import {
  appendChatMessage,
  buildMemoryBlock,
  getCharacter,
  readChat,
  readMemoryFile,
  rewriteChatMessages,
  updateChatHeader,
  writeMemoryFile,
} from '../lib/storage'
import { streamChatCompletion, type StreamedToolCall } from '../llm/openai'
import {
  createMemorySession,
  MEMORY_TOOL_NAMES,
  executeMemoryTool,
  memoryToolDefs,
  type MemorySession,
} from '../tools/memoryTools'
import { FILE_TOOL_NAMES, executeFileTool, fileToolDefs } from '../tools/fileTools'
import { CHAT_TOOL_NAMES, chatToolDefs, executeChatTool } from '../tools/chatTools'
import {
  WEB_SEARCH_TOOL_NAMES,
  detectSearchIntent,
  executeWebSearchTool,
  webSearchToolDefs,
} from '../tools/webSearchTools'
import { firstEmotionTag } from '../../shared/emotions'
import { substituteMacros, userName, type MacroNames } from '../../shared/macros'
import type { ChatEvent, ChatMessage, ContextInfo, MessageVariant, Settings, ToolTrace } from '../../shared/types'

export const chatRouter = Router()

// Budget de la boucle d'outils d'un chat. Huit et non six : le garde-fou
// « lire avant d'écrire » des outils mémoire ajoute un aller-retour
// (memory_read puis memory_update) à chaque fait déposé sur une mémoire existante.
const MAX_TOOL_ITERATIONS = 8

interface BackendPayload {
  messages: unknown[]
  tools?: unknown[]
  model: string
  temperature: number
  max_tokens: number
}

// ── Images (modèles à vision) ──────────────────────────────────────────────
// Un message porteur d'images part en content OpenAI multimodal ; le texte, lui,
// reste une simple string dans le fichier de chat (ChatMessage.content).

/** Partie d'un content multimodal OpenAI. */
export type ContentPart = { type: 'text'; text: string } | { type: 'image_url'; image_url: { url: string } }

/** Content OpenAI d'un message : le texte seul, ou le tableau multimodal si des images l'accompagnent. */
function messageContent(m: ChatMessage): string | ContentPart[] {
  return m.images && m.images.length > 0 ? multimodalContent(m.content, m.images) : m.content
}

/** [texte ?, image, image…] — la partie texte est omise quand il n'y a pas de texte. */
export function multimodalContent(text: string, images: string[]): ContentPart[] {
  const parts: ContentPart[] = []
  if (text) parts.push({ type: 'text', text })
  for (const url of images) parts.push({ type: 'image_url', image_url: { url } })
  return parts
}

// ── Macros des cards ───────────────────────────────────────────────────────
// {{char}} / {{user}} (et <BOT> / <USER>) sont substitués ICI, à la
// construction du payload : les fichiers du disque gardent leurs macros, seul
// ce qui PART vers le modèle est résolu. Le prompt du personnage renvoyé à
// l'inspecteur reste donc la source, éditable telle quelle.

/** Noms substitués : le personnage, et l'utilisateur tel que sa persona le nomme. */
function macroNamesFor(characterName: string, settings: Settings): MacroNames {
  return { char: characterName, user: userName(settings.personaName) }
}

/**
 * Bloc persona : qui est l'utilisateur, tel qu'il s'est décrit dans les
 * réglages. Faits bruts (en anglais, langue de travail des prompts), AUCUNE
 * directive ajoutée — comme le bloc heure et les notes de scène. Les deux
 * champs sont indépendants : un nom seul, une description seule, ou les deux.
 */
function personaBlock(name: string, description: string): string {
  let block = '\n\n## The user (persona, set by the user in Hanami settings)\n'
  if (name) block += `The user's name is ${name}.\n`
  if (description) block += `${description}\n`
  return block
}

/** Substitution dans un content OpenAI : texte seul, ou parties texte d'un multimodal. */
function subContent(content: string | ContentPart[], names: MacroNames): string | ContentPart[] {
  if (typeof content === 'string') return substituteMacros(content, names)
  return content.map((p) => (p.type === 'text' ? { ...p, text: substituteMacros(p.text, names) } : p))
}

/** Bloc résumé de compaction injecté dans le system prompt (visible dans l'inspecteur). */
function summaryBlock(summary: string): string {
  return `\n\n## Conversation summary (auto-generated by Hanami compaction — earlier messages were condensed into this)\n\n${summary}`
}

/**
 * Bloc notes de scène de la conversation : le texte de l'utilisateur, RIEN de plus
 * (pas de directive ajoutée). Champ vide = bloc absent, donc zéro injection.
 */
function sceneNotesBlock(notes: string): string {
  return `\n\n## Scene notes (set by the user for this conversation)\n\n${notes}`
}

/** Plafond des notes de scène — c'est une note d'ambiance, pas un second prompt. */
const SCENE_NOTES_MAX_CHARS = 2000

// Coût forfaitaire d'une image. Une data URL pèse des centaines de milliers de
// caractères pour quelques centaines de tokens réels : la compter au caractère
// ferait exploser la jauge de contexte ET le budget de compaction.
const IMAGE_TOKENS = 800

/**
 * Copie de la valeur où chaque data URL d'image devient un jeton court, plus le
 * nombre d'images rencontrées. Vaut pour les deux formes : le `image_url.url`
 * d'un content multimodal et le `images[]` d'un ChatMessage brut.
 */
function withoutImageData(value: unknown): { lean: unknown; images: number } {
  let images = 0
  const walk = (v: unknown): unknown => {
    if (typeof v === 'string') {
      if (!v.startsWith('data:image/')) return v
      images++
      return '[image]'
    }
    if (Array.isArray(v)) return v.map(walk)
    if (v !== null && typeof v === 'object') {
      const out: Record<string, unknown> = {}
      for (const [k, child] of Object.entries(v as Record<string, unknown>)) out[k] = walk(child)
      return out
    }
    return v
  }
  const lean = walk(value)
  return { lean, images }
}

/** Estimation grossière du volume de tokens (~4 caractères/token sur le JSON, forfait par image). */
function estimateTokens(value: unknown): number {
  const { lean, images } = withoutImageData(value)
  return Math.ceil(JSON.stringify(lean).length / 4) + images * IMAGE_TOKENS
}

/** Écart humanisé entre deux messages (en anglais : langue de travail des prompts). */
function humanizeGap(ms: number): string {
  const min = Math.floor(ms / 60000)
  if (min < 1) return 'less than a minute'
  if (min < 60) return `${min} minute${min > 1 ? 's' : ''}`
  const h = Math.floor(min / 60)
  if (h < 48) return `${h} hour${h > 1 ? 's' : ''}`
  return `${Math.floor(h / 24)} days`
}

// Bloc temporel : le personnage sait QUAND on lui parle (matin/soir, retour
// après des jours…). Faits bruts en anglais — le modèle les exprime dans la
// langue de la conversation. Visible dans l'inspecteur comme tout le reste.
const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

function timeBlock(lastMessageTs: string | null): string {
  const now = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  // Timezone NOMMÉE (et non « user's local time ») : un ancrage explicite que
  // le modèle peut vérifier, au lieu d'une notion à deviner.
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || 'local time'
  let block =
    '\n\n## Current date and time (auto-injected by Hanami — the only authoritative source)\n' +
    `Now: ${WEEKDAYS[now.getDay()]} ${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}, ` +
    `${pad(now.getHours())}:${pad(now.getMinutes())} (${tz}, the user's local time).\n`
  if (lastMessageTs) {
    const gap = now.getTime() - new Date(lastMessageTs).getTime()
    if (Number.isFinite(gap) && gap >= 0) {
      block += `Time since the previous message in this conversation: ${humanizeGap(gap)}.\n`
    }
  }
  // L'ancienne consigne « never recite it » faisait échouer la question directe
  // « quelle heure est-il ? » : le modèle généralisait « ne pas réciter » à
  // « ne pas répondre ». D'où l'autorisation explicite ci-dessous, et la phrase
  // d'autorité : les modèles locaux ont tendance à répondre une date de leur
  // données d'entraînement si on ne leur impose pas celle d'ici.
  block +=
    'Your training data does not know the current date or time — trust ONLY the values above, never a date you may "remember".\n' +
    'If the user asks what day, date or time it is, answer directly and exactly with those values, ' +
    'in the language of the conversation. Otherwise let them shape your replies naturally ' +
    '(greetings, time of day, absences) without reciting them.\n'
  return block
}

/**
 * Construit le payload EXACT envoyé au backend (aussi renvoyé tel quel par
 * /api/prompt-preview, et réutilisé par le moteur de messages spontanés).
 *
 * Le texte système est rendu en DEUX morceaux en plus du tout :
 * `characterPrompt` (le prompt du personnage, celui qui s'écrit et se corrige)
 * et `injected` (ce que Hanami ajoute : mémoire, résumé, notes de scène,
 * heure). L'inspecteur s'en sert pour rendre le premier ÉDITABLE sur place,
 * sans avoir à deviner où finit l'un et où commence l'autre.
 *
 * Nuance depuis les macros : ces deux morceaux sont la SOURCE, macros comprises
 * ({{char}}, {{user}}) — `systemText` et `payload`, eux, sont résolus. Écrire
 * l'un par-dessus l'autre figerait les macros dans le fichier du personnage.
 */
export function buildPayload(
  characterId: string,
  chatId: string,
  settings: Settings,
  // string = message (ou consigne) purement textuel ; tableau = message courant
  // accompagné d'images (content multimodal OpenAI).
  pendingUserContent?: string | ContentPart[],
  // Régénération : la réponse à refaire est encore DANS le fichier (elle y reste,
  // elle va devenir une variante) — elle est simplement retirée de l'historique
  // envoyé, sinon le modèle réécrirait par-dessus sa propre copie.
  omitLastMessage = false,
): { systemText: string; characterPrompt: string; injected: string; payload: BackendPayload } {
  const character = getCharacter(characterId)
  if (!character) throw new Error(`Personnage introuvable : ${characterId}`)
  const characterPrompt = character.systemPrompt
  let injected = ''
  // La persona vient EN TÊTE des blocs ajoutés : savoir à qui l'on parle
  // précède ce dont on se souvient de lui.
  const personaName = settings.personaName.trim()
  const personaDescription = settings.personaDescription.trim()
  if (personaName || personaDescription) injected += personaBlock(personaName, personaDescription)
  if (settings.memoryEnabled) injected += buildMemoryBlock(characterId, settings.modelMode === 'simple')

  const { meta, messages: all } = readChat(characterId, chatId)
  const history = omitLastMessage ? all.slice(0, -1) : all
  // Conversation compactée : le résumé (dans le system) remplace les messages qu'il couvre.
  const upto = meta.summary ? Math.min(meta.summaryUpto ?? 0, history.length) : 0
  if (meta.summary) injected += summaryBlock(meta.summary)
  if (meta.sceneNotes) injected += sceneNotesBlock(meta.sceneNotes)
  if (settings.timeAwareness) {
    injected += timeBlock(history.length > 0 ? history[history.length - 1].ts : null)
  }
  // Macros résolues sur TOUT ce qui part : le texte système (prompt du
  // personnage ET blocs ajoutés — une note de scène peut dire « {{char}} »),
  // l'historique et le message courant. `characterPrompt` reste brut plus bas :
  // c'est la source que l'inspecteur rend éditable.
  const names = macroNamesFor(character.name, settings)
  const systemText = substituteMacros(characterPrompt + injected, names)
  const live = history.slice(upto)
  const recent = settings.maxHistoryMessages > 0 ? live.slice(-settings.maxHistoryMessages) : []
  const messages: unknown[] = [
    { role: 'system', content: systemText },
    // Un message d'historique porteur d'images repart en multimodal : le modèle
    // à vision revoit donc les images des tours précédents.
    ...recent.map((m) => ({ role: m.role, content: subContent(messageContent(m), names) })),
  ]
  if (pendingUserContent !== undefined) {
    messages.push({ role: 'user', content: subContent(pendingUserContent, names) })
  }

  // Mode simple : AUCUN outil n'est exposé (le tool-calling est le talon d'Achille
  // des petits modèles). Le bloc mémoire, lui, reste injecté — il se lit sans outil.
  const tools: unknown[] =
    settings.modelMode === 'simple'
      ? []
      : [
          // chat_search voyage avec la mémoire : c'est le même « souvenir de l'autre ».
          ...(settings.memoryEnabled ? [...memoryToolDefs, ...chatToolDefs] : []),
          ...(settings.fileToolsEnabled ? fileToolDefs : []),
          ...(settings.webSearchEnabled ? webSearchToolDefs : []),
        ]
  const payload: BackendPayload = {
    messages,
    model: settings.model,
    temperature: settings.temperature,
    max_tokens: settings.maxTokens,
  }
  if (tools.length > 0) payload.tools = tools
  return { systemText, characterPrompt, injected, payload }
}

// ── Impersonate ─────────────────────────────────────────────────────────────
// « Écrire à la place de l'utilisateur » — PAS un simple ajout en fin du prompt
// du personnage (le piège de SillyTavern, qui laisse la persona du perso
// dominer) : le system prompt est ici reconstruit avec l'UTILISATEUR comme
// locuteur et {{char}} comme interlocuteur, et l'historique est ÉCHANGÉ
// (assistant ↔ user) — le modèle, qui complète toujours le rôle « assistant »,
// écrit donc naturellement dans SA voix à lui. characterPrompt (les
// instructions de rôle du personnage) n'entre JAMAIS dans ce payload : c'est
// justement lui qu'il faut faire taire pour que la persona utilisateur tienne.

const IMPERSONATE_LENGTH_SAMPLE = 12 // derniers tours utilisateur considérés représentatifs

/** Longueur (caractères) typique des messages récents de l'utilisateur — null si aucun. */
function typicalUserLength(history: ChatMessage[]): number | null {
  const lens = history
    .filter((m) => m.role === 'user' && m.content.trim())
    .slice(-IMPERSONATE_LENGTH_SAMPLE)
    .map((m) => m.content.trim().length)
  if (lens.length === 0) return null
  return Math.round(lens.reduce((a, b) => a + b, 0) / lens.length)
}

/** System prompt d'impersonation : l'utilisateur EST le locuteur, {{char}} est l'autre. */
function impersonateSystemPrompt(
  characterName: string,
  personaName: string,
  personaDescription: string,
  typicalLen: number | null,
): string {
  const who = personaName || 'the user'
  let block = `You are ${who}, a real person in an ongoing conversation with ${characterName}.\n`
  if (personaDescription) block += `About you: ${personaDescription}\n`
  block +=
    `\nWrite YOUR OWN next message to ${characterName} — from your own point of view, in your own voice, ` +
    `never theirs. Below, ${characterName}'s turns are tagged "user" and yours are tagged "assistant", so that ` +
    `you naturally continue as yourself when completing the assistant turn.\n` +
    `Match your own tone, habits and phrasing as shown earlier in the conversation.`
  if (typicalLen !== null) {
    block += ` Your messages usually run about ${typicalLen} characters long — stay close to that, don't ramble.`
  }
  block += ' Reply with ONLY that message: no narration, no emotion tags, no meta-commentary.'
  return block
}

/**
 * Payload d'impersonation : réutilise les blocs neutres de buildPayload
 * (résumé, notes de scène, heure — de simples faits, jamais des instructions
 * de rôle) mais jamais characterPrompt, et échange les rôles de l'historique.
 * Aucun outil exposé : impersonate écrit une réplique, jamais une action.
 */
function buildImpersonatePayload(
  characterId: string,
  chatId: string,
  settings: Settings,
): { payload: BackendPayload } {
  const character = getCharacter(characterId)
  if (!character) throw new Error(`Personnage introuvable : ${characterId}`)
  const { meta, messages: all } = readChat(characterId, chatId)
  const names = macroNamesFor(character.name, settings)

  let injected = ''
  if (meta.summary) injected += summaryBlock(meta.summary)
  if (meta.sceneNotes) injected += sceneNotesBlock(meta.sceneNotes)
  if (settings.timeAwareness) injected += timeBlock(all.length > 0 ? all[all.length - 1].ts : null)

  const base = impersonateSystemPrompt(
    character.name,
    settings.personaName.trim(),
    settings.personaDescription.trim(),
    typicalUserLength(all),
  )
  const systemText = substituteMacros(base + injected, names)

  const upto = meta.summary ? Math.min(meta.summaryUpto ?? 0, all.length) : 0
  const live = all.slice(upto)
  const recent = settings.maxHistoryMessages > 0 ? live.slice(-settings.maxHistoryMessages) : []
  const messages: unknown[] = [
    { role: 'system', content: systemText },
    // Perspective inversée : le tour de {{char}} devient "user", celui de
    // l'utilisateur devient "assistant" — voir le commentaire de section plus haut.
    ...recent.map((m) => ({
      role: m.role === 'assistant' ? 'user' : 'assistant',
      content: subContent(messageContent(m), names),
    })),
  ]
  return {
    payload: { messages, model: settings.model, temperature: settings.temperature, max_tokens: settings.maxTokens },
  }
}

function toAssistantMessage(text: string, thinking?: string): ChatMessage {
  const emotion = firstEmotionTag(text)
  const msg: ChatMessage = { role: 'assistant', content: text, ts: new Date().toISOString() }
  if (emotion) msg.emotion = emotion
  if (thinking) msg.thinking = thinking
  return msg
}

// Résultat plafonné pour la PERSISTANCE : un read_file peut faire 256 Ko et le
// .jsonl ne doit pas gonfler — la puce dépliée n'a besoin que du début du
// résultat. En session (event SSE), le client garde le résultat intégral.
const TRACE_RESULT_CAP = 2048
function cappedTraceResult(result: string): string {
  return result.length > TRACE_RESULT_CAP ? result.slice(0, TRACE_RESULT_CAP) + '…' : result
}

// ── Variantes de réponse ───────────────────────────────────────────────────
// « Régénérer » n'écrase plus la dernière réponse : elle devient une variante du
// MÊME message, la nouvelle s'ajoute à côté et devient celle qui est affichée.
// Aucun message n'est créé ni retiré au passage — tout tient dans la ligne.
// L'invariant (corps du message = variante affichée) se pose ici et se rejoue à
// la lecture (lib/storage.ts).

/**
 * Plafond de variantes gardées sur un message. Au-delà, la PLUS ANCIENNE
 * s'efface : une ligne de .jsonl ne doit pas enfler sans fin sous les clics.
 * L'élagage du prochain message utilisateur fait le reste du ménage.
 */
const MAX_VARIANTS = 12

/** Le corps d'un message, isolé — c'est exactement ce qu'une variante porte. */
function bodyOf(m: ChatMessage): MessageVariant {
  return {
    content: m.content,
    ts: m.ts,
    ...(m.emotion ? { emotion: m.emotion } : {}),
    ...(m.thinking ? { thinking: m.thinking } : {}),
    ...(m.tools && m.tools.length > 0 ? { tools: m.tools } : {}),
  }
}

/** Variantes d'un message — son propre corps quand il n'en porte aucune. */
function variantsOf(m: ChatMessage): MessageVariant[] {
  return m.variants && m.variants.length >= 2 ? m.variants : [bodyOf(m)]
}

/** Message reconstruit autour de la variante `index` (l'invariant du format). */
function withVariants(m: ChatMessage, variants: MessageVariant[], index: number): ChatMessage {
  const active = variants[index]
  const out: ChatMessage = { ...m, content: active.content, ts: active.ts }
  delete out.emotion
  if (active.emotion) out.emotion = active.emotion
  delete out.thinking
  if (active.thinking) out.thinking = active.thinking
  delete out.tools
  if (active.tools) out.tools = active.tools
  if (variants.length >= 2) {
    out.variants = variants
    out.variant = index
  } else {
    delete out.variants
    delete out.variant
  }
  return out
}

/**
 * ÉLAGAGE : la variante affichée reste, les autres disparaissent — le corps du
 * message ne bouge pas d'un caractère (il la recopiait déjà). Appliqué dès que
 * le fil AVANCE (nouveau message de l'utilisateur) ou qu'une réponse est éditée
 * à la main : feuilleter sert à choisir avant de continuer, pas à emporter
 * quatre versions du passé dans toute la conversation.
 */
function pruneVariants(m: ChatMessage): ChatMessage {
  if (m.variants === undefined && m.variant === undefined) return m
  const out = { ...m }
  delete out.variants
  delete out.variant
  return out
}

/**
 * Registre des outils : route l'appel vers mémoire, chat ou fichiers — et
 * REVÉRIFIE les réglages. buildPayload filtre les définitions exposées, mais un
 * modèle peut halluciner un nom d'outil jamais annoncé : sans ces gardes, un
 * write_file s'exécutait même outils fichiers désactivés. Le throw est rendu au
 * modèle comme résultat d'outil (« Erreur : … ») — transparent, jamais fatal.
 */
async function executeTool(
  characterId: string,
  settings: Settings,
  name: string,
  rawArgs: string,
  mem: MemorySession,
): Promise<string> {
  let args: Record<string, unknown>
  try {
    args = rawArgs.trim() ? (JSON.parse(rawArgs) as Record<string, unknown>) : {}
  } catch {
    throw new Error(`invalid JSON arguments for ${name}`)
  }
  if ((MEMORY_TOOL_NAMES as readonly string[]).includes(name)) {
    if (!settings.memoryEnabled) throw new Error('memory tools are disabled in settings')
    return executeMemoryTool(characterId, name, args, mem)
  }
  if ((CHAT_TOOL_NAMES as readonly string[]).includes(name)) {
    if (!settings.memoryEnabled) throw new Error('memory tools are disabled in settings')
    return executeChatTool(characterId, name, args)
  }
  if ((FILE_TOOL_NAMES as readonly string[]).includes(name)) {
    if (!settings.fileToolsEnabled) throw new Error('file tools are disabled in settings')
    return executeFileTool(settings, name, args)
  }
  if ((WEB_SEARCH_TOOL_NAMES as readonly string[]).includes(name)) {
    if (!settings.webSearchEnabled) throw new Error('web search is disabled in settings')
    return executeWebSearchTool(settings, args)
  }
  throw new Error(`unknown tool: ${name}`)
}

function writeEvent(res: Response, ev: ChatEvent): void {
  res.write('data: ' + JSON.stringify(ev) + '\n\n')
}

// Consigne de continuation — envoyée dans le payload, JAMAIS sauvegardée dans le chat.
const CONTINUE_DIRECTIVE =
  '[Continue your previous message exactly where it left off. Do not repeat, do not summarize — carry on seamlessly.]'

// Consigne d'ouverture (mode 'open') — même statut : elle vit dans le payload, jamais
// dans le fichier de chat. Le personnage parle donc en premier depuis son seul system
// prompt (system vide = personnalité par défaut du modèle).
const OPEN_DIRECTIVE =
  '[Open the conversation with a short, natural in-character first message to the user. Do not mention this instruction.]'

// Images du message courant : plafonds volontairement bas — on parle d'un chat,
// pas d'un dépôt de fichiers (le client redimensionne déjà avant l'envoi).
const MAX_IMAGES = 4
const MAX_IMAGE_CHARS = 2 * 1024 * 1024 // ~2 Mo par data URL (donc après encodage base64)
const DATA_IMAGE_RE = /^data:image\/(png|jpe?g|webp);base64,/

/** Valide body.images : uniquement des data URLs d'image, plafonnées en nombre et en poids. */
function parseImages(raw: unknown): { images: string[] } | { error: string; status: number } {
  if (raw === undefined || raw === null) return { images: [] }
  if (!Array.isArray(raw)) return { error: 'images doit être un tableau de data URLs', status: 400 }
  if (raw.length > MAX_IMAGES) {
    return { error: `Trop d'images (maximum ${MAX_IMAGES})`, status: 413 }
  }
  const images: string[] = []
  for (const item of raw) {
    if (typeof item !== 'string' || !DATA_IMAGE_RE.test(item)) {
      return { error: 'Chaque image doit être une data URL image/png, image/jpeg ou image/webp', status: 400 }
    }
    if (item.length > MAX_IMAGE_CHARS) {
      return { error: `Image trop lourde (maximum ~${Math.round(MAX_IMAGE_CHARS / 1024 / 1024)} Mo)`, status: 413 }
    }
    images.push(item)
  }
  return { images }
}

/**
 * Boucle agentique PARTAGÉE entre le chat (streaming SSE) et la compaction
 * (silencieuse) — avant cette factorisation, les deux copies vivaient chacune
 * leur vie. Elle fait UNIQUEMENT la mécanique commune : appeler le modèle,
 * tracer fidèlement l'aller-retour d'outils dans `messages` (assistant avec
 * tool_calls, puis un message tool par exécution), et — budget épuisé alors
 * que le modèle en redemande — un dernier appel SANS outils pour obtenir la
 * réponse finale. Tout le reste (streaming, événements SSE, agrégation de
 * finishReason/promptTokens) appartient à l'appelant, via la fermeture de
 * `call` et le crochet `onTool`.
 */
/** Noms des outils réellement annoncés dans un tableau de définitions OpenAI. */
function toolNamesOf(tools: unknown[] | undefined): ReadonlySet<string> {
  const names = new Set<string>()
  for (const t of tools ?? []) {
    const name = (t as { function?: { name?: unknown } }).function?.name
    if (typeof name === 'string' && name) names.add(name)
  }
  return names
}

async function runToolLoop<R extends { content: string; toolCalls: StreamedToolCall[] }>(
  characterId: string,
  settings: Settings,
  messages: unknown[],
  maxIterations: number,
  // Seuls les outils ANNONCÉS dans la requête sont exécutables : un nom
  // halluciné (ou hors du périmètre de la compaction) devient une erreur
  // d'outil rendue au modèle, jamais une exécution.
  allowed: ReadonlySet<string>,
  // Fichiers mémoire lus pendant CETTE requête — le garde-fou « lire avant
  // d'écrire » de memoryTools s'appuie dessus.
  mem: MemorySession,
  call: (withTools: boolean) => Promise<R>,
  onTool?: (name: string, args: string, result: string) => void,
  onToolStart?: (name: string, args: string) => void,
): Promise<{ last: R; exhausted: boolean }> {
  let last = await call(true)
  for (let iteration = 1; ; iteration++) {
    if (last.toolCalls.length === 0) return { last, exhausted: false }
    // Trace fidèle de l'aller-retour outil dans le contexte de la boucle.
    messages.push({
      role: 'assistant',
      content: last.content || null,
      tool_calls: last.toolCalls.map((tc) => ({
        id: tc.id,
        type: 'function',
        function: { name: tc.name, arguments: tc.arguments },
      })),
    })
    for (const tc of last.toolCalls) {
      let toolResult: string
      if (!allowed.has(tc.name)) {
        toolResult = `Error: tool not offered in this request: ${tc.name}`
      } else {
        // Signalé AVANT l'exécution : l'interface anime la puce pendant
        // l'action (sans elle, le fil semble figé tant que le modèle
        // n'a pas « fini » de parler).
        onToolStart?.(tc.name, tc.arguments)
        try {
          toolResult = await executeTool(characterId, settings, tc.name, tc.arguments, mem)
        } catch (e) {
          toolResult = `Error: ${e instanceof Error ? e.message : String(e)}`
        }
      }
      onTool?.(tc.name, tc.arguments, toolResult)
      messages.push({ role: 'tool', tool_call_id: tc.id, content: toolResult })
    }
    if (iteration >= maxIterations) {
      // Budget épuisé, le modèle veut encore des outils : réponse finale sans eux.
      return { last: await call(false), exhausted: true }
    }
    last = await call(true)
  }
}

async function handleChat(req: Request, res: Response): Promise<void> {
  const body = (req.body ?? {}) as {
    characterId?: unknown
    chatId?: unknown
    content?: unknown
    images?: unknown
    mode?: unknown
    forceSearch?: unknown
  }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const content = typeof body.content === 'string' ? body.content : ''
  // /search du composer : force une recherche web AVANT le premier appel au
  // modèle (voir plus bas), au lieu de compter sur le modèle pour décider d'y
  // recourir. Sans effet hors message normal (mode défini, ou recherche web
  // désactivée/indisponible) — /search dégrade alors en simple message.
  const forceSearch = body.forceSearch === true
  const mode =
    body.mode === 'regenerate' || body.mode === 'continue' || body.mode === 'open' || body.mode === 'impersonate'
      ? body.mode
      : undefined
  // Validé avant toute autre chose : la réponse est encore du JSON à ce stade
  // (une fois le flux SSE ouvert, plus aucun code d'erreur HTTP n'est possible).
  const parsedImages = parseImages(body.images)
  if ('error' in parsedImages) {
    res.status(parsedImages.status).json({ error: parsedImages.error })
    return
  }
  // Les images n'appartiennent qu'au message COURANT : régénérer/continuer/ouvrir
  // rejoue l'historique, qui porte déjà les siennes.
  const images = mode ? [] : parsedImages.images
  // Une image seule est un message légitime (le texte peut être vide).
  if (!characterId || !chatId || (!content && !mode && images.length === 0)) {
    res.status(400).json({ error: 'characterId, chatId et content (ou images, ou mode) sont requis' })
    return
  }
  const settings = loadSettings()
  if (!getCharacter(characterId)) {
    res.status(404).json({ error: `Personnage introuvable : ${characterId}` })
    return
  }
  let existing: ChatMessage[]
  try {
    existing = readChat(characterId, chatId).messages
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }

  // Base d'une continuation : le dernier message assistant, complété en place.
  let continueBase: ChatMessage | null = null
  // Base d'une régénération : la réponse actuelle, qui NE SORT PAS du fichier —
  // elle deviendra une variante du même message une fois la nouvelle écrite.
  let regenBase: ChatMessage | null = null
  // Régénérer un premier message généré : la conversation redevient vide, le payload
  // reprend donc la consigne d'ouverture (sinon le modèle n'aurait aucun tour user).
  let regenOpens = false
  if (mode === 'regenerate') {
    if (existing.length === 0) {
      res.status(400).json({ error: 'Rien à régénérer (conversation vide)' })
      return
    }
    // Dernier message = réponse de l'assistant → nouvelle VARIANTE de ce message.
    // Le fichier n'est pas touché ici : la réponse actuelle est seulement retirée
    // de l'historique envoyé (omitLastMessage), et l'épingle — qui vise un
    // message toujours présent, au même rang — n'a plus de raison d'être levée.
    // (Dernier message = user, ex. génération précédente échouée → on rejoue tel quel.)
    if (existing[existing.length - 1].role === 'assistant') {
      regenBase = existing[existing.length - 1]
      regenOpens = existing.length === 1
    }
  } else if (mode === 'continue') {
    const last = existing[existing.length - 1]
    if (!last || last.role !== 'assistant') {
      res.status(400).json({ error: 'Rien à continuer (le dernier message n’est pas une réponse)' })
      return
    }
    continueBase = last
  } else if (mode === 'open' && existing.length > 0) {
    // Le premier message ne se génère que dans une conversation encore vierge.
    res.status(400).json({ error: "La conversation n'est pas vide (rien à ouvrir)" })
    return
  } else if (mode === 'impersonate' && existing.length === 0) {
    // Impersonate a besoin d'au moins un tour à imiter (ton, longueur, sujet).
    res.status(400).json({ error: 'Rien à impersonner (conversation vide)' })
    return
  }

  // Payload construit AVANT la sauvegarde : le message courant passe par pendingUserContent,
  // sinon il consommerait un slot d'historique (et ne serait jamais envoyé si
  // maxHistoryMessages = 0).
  const pendingUser: string | ContentPart[] | undefined =
    mode === 'continue'
      ? CONTINUE_DIRECTIVE
      : mode === 'open' || regenOpens
        ? OPEN_DIRECTIVE
        : mode === 'regenerate' || mode === 'impersonate'
          ? undefined
          : images.length > 0
            ? multimodalContent(content, images)
            : content
  // Impersonate ne passe JAMAIS par buildPayload : son system prompt et son
  // historique (rôles échangés) sont d'une nature différente — voir buildImpersonatePayload.
  const { payload } =
    mode === 'impersonate'
      ? buildImpersonatePayload(characterId, chatId, settings)
      : buildPayload(characterId, chatId, settings, pendingUser, regenBase !== null)
  const messages = payload.messages as Record<string, unknown>[]

  // Le message user est sauvegardé AVANT l'appel backend : il survit à toute erreur en aval.
  if (!mode) {
    // Le fil AVANCE : les variantes non affichées de la réponse précédente sont
    // élaguées (cf. pruneVariants). Aucun message n'entre ni ne sort — les
    // repères qui comptent des messages (épingle, summaryUpto) ne bougent pas.
    if (existing.some((m) => m.variants !== undefined)) {
      rewriteChatMessages(characterId, chatId, (msgs) => msgs.map(pruneVariants))
    }
    const userMsg: ChatMessage = { role: 'user', content, ts: new Date().toISOString() }
    if (images.length > 0) userMsg.images = images
    appendChatMessage(characterId, chatId, userMsg)
  }

  res.setHeader('Content-Type', 'text/event-stream')
  res.setHeader('Cache-Control', 'no-cache')
  res.setHeader('Connection', 'keep-alive')
  res.flushHeaders()

  const abort = new AbortController()
  // Déconnexion client en plein stream → on coupe l'appel backend.
  // res 'close' + writableEnded, car req 'close' se déclenche dès la fin du body en Node ≥ 15.
  res.on('close', () => {
    if (!res.writableEnded) abort.abort()
  })

  // Recherche forcée AVANT tout appel au modèle — un aller-retour d'outil
  // authentique (assistant tool_calls + tool) est inséré dans `messages`,
  // exactement comme si le modèle avait choisi d'appeler l'outil lui-même.
  // « Forcer » veut dire ne pas dépendre de sa décision : le modèle garde la
  // main pour chercher PLUS s'il le juge utile (l'outil reste exposé).
  // Deux déclencheurs : /search explicite (tout `content` = la requête), ou —
  // filet indépendant du modèle — une intention de recherche EXPLICITE
  // détectée dans un message normal (« cherche sur le web… », « google it »…) :
  // certains modèles préfèrent « jouer » la recherche en roleplay plutôt que
  // d'appeler l'outil ; ce filet la garantit quand même.
  // Journal d'activité de la génération : chaque action exécutée y est notée,
  // puis rattachée au message persisté (l'affichage en fait les puces — jamais
  // renvoyé au backend, cf. shared/types.ts).
  const toolTraces: ToolTrace[] = []

  const trimmedContent = content.trim()
  const forcedQuery = forceSearch
    ? trimmedContent
    : !mode && trimmedContent
      ? detectSearchIntent(trimmedContent)
      : null
  if (!mode && forcedQuery && settings.webSearchEnabled && settings.modelMode !== 'simple') {
    const query = forcedQuery
    const toolCallId = `search_${Date.now()}`
    const searchArgs = JSON.stringify({ query })
    writeEvent(res, { type: 'tool_start', name: 'web_search', args: searchArgs })
    let result: string
    try {
      result = await executeWebSearchTool(settings, { query })
    } catch (e) {
      result = `Erreur : ${e instanceof Error ? e.message : String(e)}`
    }
    messages.push({
      role: 'assistant',
      content: null,
      tool_calls: [{ id: toolCallId, type: 'function', function: { name: 'web_search', arguments: searchArgs } }],
    })
    messages.push({ role: 'tool', tool_call_id: toolCallId, content: result })
    toolTraces.push({ name: 'web_search', args: searchArgs, result: cappedTraceResult(result) })
    writeEvent(res, { type: 'tool', name: 'web_search', args: searchArgs, result })
  }

  let assistantText = ''
  let assistantThinking = ''

  // Un appel streaming. Entre deux itérations, un séparateur "\n\n" est inséré dans le texte
  // ET émis comme delta : le flux affiché et le texte sauvegardé restent identiques.
  const streamOnce = (withTools: boolean) => {
    let firstDelta = true
    let firstThinking = true
    return streamChatCompletion({
      settings,
      messages,
      tools: withTools ? payload.tools : undefined,
      signal: abort.signal,
      onDelta: (text) => {
        if (firstDelta) {
          firstDelta = false
          if (assistantText.length > 0) {
            assistantText += '\n\n'
            writeEvent(res, { type: 'delta', text: '\n\n' })
          }
        }
        assistantText += text
        writeEvent(res, { type: 'delta', text })
      },
      onThinking: (text) => {
        if (firstThinking) {
          firstThinking = false
          if (assistantThinking.length > 0) assistantThinking += '\n\n'
        }
        assistantThinking += text
        writeEvent(res, { type: 'thinking', text })
      },
    })
  }

  // Sauvegarde de la sortie : continuation → fusionnée dans le dernier message
  // assistant (en place, timestamp d'origine conservé) ; sinon → message ajouté.
  // La fusion vérifie l'IDENTITÉ du message visé (ts + contenu), pas seulement
  // son rôle : le stream est la seule fenêtre asynchrone du fichier, et un
  // message spontané (même processus) peut s'ajouter pendant qu'il coule —
  // écraser le dernier venu perdrait SON texte. Fil bougé → la continuation
  // est AJOUTÉE en message à part : rien d'écrasé, rien de perdu, et le `done`
  // renvoie ce qui est réellement sur le disque.
  const persistAssistant = (): ChatMessage => {
    if (mode === 'impersonate') {
      // Jamais écrit sur le disque : impersonate ne fait qu'écrire dans le
      // composer du client (à éditer avant envoi) — la conversation elle-même
      // n'avance pas d'un message. `role: 'user'` par cohérence de type
      // seulement, rien n'est lu au-delà de `content` côté client.
      return { role: 'user', content: assistantText, ts: new Date().toISOString() }
    }
    if (mode === 'continue' && continueBase) {
      const base = continueBase
      const joiner = base.content.endsWith('\n') || assistantText.startsWith('\n') ? '' : ' '
      let merged: ChatMessage = { ...base, content: base.content + joiner + assistantText }
      const mergedEmotion = firstEmotionTag(merged.content)
      if (mergedEmotion) merged.emotion = mergedEmotion
      if (assistantThinking) {
        merged.thinking = base.thinking ? base.thinking + '\n\n' + assistantThinking : assistantThinking
      }
      // Les actions de la passée de continuation s'ajoutent au journal de la
      // variante affichée (le corps du message la recopie — cf. invariant).
      if (toolTraces.length > 0) merged.tools = [...(base.tools ?? []), ...toolTraces]
      // Le message porte des variantes : c'est la variante AFFICHÉE qui s'allonge
      // (« Continuer » continue ce qu'on lit) — les autres restent feuilletables.
      const active = merged.variant
      if (merged.variants && typeof active === 'number') {
        const grown = merged.variants.map((v, i) => (i === active ? bodyOf(merged) : v))
        merged = withVariants(merged, grown, active)
      }
      const continued = merged
      let saved: ChatMessage = continued
      rewriteChatMessages(characterId, chatId, (msgs) => {
        const lastMsg = msgs[msgs.length - 1]
        if (lastMsg && lastMsg.role === 'assistant' && lastMsg.ts === base.ts && lastMsg.content === base.content) {
          msgs[msgs.length - 1] = continued
          return msgs
        }
        saved = toAssistantMessage(assistantText, assistantThinking)
        if (toolTraces.length > 0) saved.tools = [...toolTraces]
        msgs.push(saved)
        return msgs
      })
      return saved
    }
    const message = toAssistantMessage(assistantText, assistantThinking)
    if (toolTraces.length > 0) message.tools = [...toolTraces]
    // Régénération : la nouvelle réponse rejoint les précédentes DANS le message,
    // et devient celle qui est affichée. Comme pour la continuation, l'IDENTITÉ
    // du message visé est vérifiée (ts + contenu) : un message spontané a pu
    // s'ajouter pendant le stream — fil bougé, la réponse est alors simplement
    // AJOUTÉE, rien n'est écrasé.
    if (mode === 'regenerate' && regenBase) {
      const base = regenBase
      // Génération VIDE (budget de sortie parti dans le raisonnement, coupure
      // nette) : aucune variante à ajouter — la réponse en place reste, et rien
      // n'est réécrit. Sans ce garde-fou, une variante vide deviendrait la
      // variante affichée et masquerait une bonne réponse derrière une flèche.
      if (assistantText.length === 0) return base
      let saved: ChatMessage = message
      rewriteChatMessages(characterId, chatId, (msgs) => {
        const lastMsg = msgs[msgs.length - 1]
        if (lastMsg && lastMsg.role === 'assistant' && lastMsg.ts === base.ts && lastMsg.content === base.content) {
          const list = [...variantsOf(lastMsg), bodyOf(message)].slice(-MAX_VARIANTS)
          saved = withVariants(lastMsg, list, list.length - 1)
          msgs[msgs.length - 1] = saved
          return msgs
        }
        msgs.push(message)
        return msgs
      })
      return saved
    }
    appendChatMessage(characterId, chatId, message)
    return message
  }

  try {
    let truncated = false
    let finishReason = ''
    let promptTokens = 0

    // Les agrégations (truncated, finishReason, promptTokens — le dernier usage
    // NON NUL fait foi) restent ici, par fermeture : la boucle partagée ne
    // s'occupe que de la mécanique d'outils.
    const mem = createMemorySession() // lectures mémoire de CETTE requête (garde-fou)
    const { exhausted } = await runToolLoop(
      characterId,
      settings,
      messages,
      MAX_TOOL_ITERATIONS,
      toolNamesOf(payload.tools),
      mem,
      async (withTools) => {
        const result = await streamOnce(withTools)
        truncated = result.truncated
        finishReason = result.finishReason
        if (result.promptTokens > 0) promptTokens = result.promptTokens
        return result
      },
      (name, args, toolResult) => {
        writeEvent(res, { type: 'tool', name, args, result: toolResult })
        toolTraces.push({ name, args, result: cappedTraceResult(toolResult) })
      },
      (name, args) => {
        writeEvent(res, { type: 'tool_start', name, args })
      },
    )

    if (exhausted && assistantText.length === 0) {
      // Rien à sauvegarder : pas de message vide, pas de done.
      writeEvent(res, { type: 'error', message: "Budget d'outils épuisé sans réponse du modèle" })
      res.end()
      return
    }

    // Contenu INTÉGRAL, tel que généré (le tag d'émotion reste dans le texte).
    const message = persistAssistant()
    // Jauge de contexte : usage réel du backend quand il le fournit, sinon
    // estimation sur le payload final (qui inclut les allers-retours d'outils
    // ET les définitions d'outils, comptées par l'usage réel elles aussi).
    const tokens =
      (promptTokens > 0 ? promptTokens : estimateTokens(messages) + estimateTokens(payload.tools ?? [])) +
      estimateTokens(assistantText)
    // Fenêtre de TRAVAIL (plafonnée) et non le contexte complet du modèle :
    // avec une fenêtre de 262k, la jauge plafonnait à ~15 % et l'auto-compaction
    // ne se déclenchait jamais (voir workingWindow dans config.ts).
    const limit = workingWindow(settings)
    const context: ContextInfo = {
      tokens,
      limit,
      percent: limit > 0 ? Math.min(100, Math.round((tokens / limit) * 100)) : 0,
    }
    writeEvent(res, { type: 'done', message, context })
    // Signalé APRÈS la sauvegarde et le done : le client affiche la bulle d'erreur discrète.
    if (truncated || finishReason === 'length') {
      writeEvent(res, {
        type: 'error',
        message: truncated
          ? 'Réponse probablement tronquée (flux interrompu avant la fin)'
          : 'Réponse coupée (max_tokens atteint)',
      })
    }
    res.end()
  } catch (e) {
    if (abort.signal.aborted) {
      // Client parti : on sauvegarde le partiel si au moins un delta est arrivé.
      if (assistantText.length > 0) persistAssistant()
      try {
        res.end()
      } catch {
        /* socket déjà fermée */
      }
      return
    }
    const message = e instanceof Error ? e.message : String(e)
    if (assistantText.length > 0) {
      // Erreur mi-flux : le partiel déjà affiché côté client est sauvegardé, et joint à l'événement.
      const partial = persistAssistant()
      writeEvent(res, { type: 'error', message, partial })
    } else {
      writeEvent(res, { type: 'error', message })
    }
    res.end()
  }
}

// Verrou par chat du mode 'open' : le premier message d'une conversation vide
// peut être demandé deux fois (deux appareils ouverts, double clic) et la
// conversation se retrouverait avec DEUX ouvertures empilées.
const opensInFlight = new Set<string>()

chatRouter.post('/api/chat', async (req, res) => {
  // Verrou posé AVANT handleChat : dès que le flux SSE est ouvert, plus aucun
  // code d'erreur HTTP n'est possible.
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; mode?: unknown }
  const openKey =
    body.mode === 'open' && typeof body.characterId === 'string' && typeof body.chatId === 'string'
      ? `${body.characterId}/${body.chatId}`
      : null
  if (openKey !== null) {
    if (opensInFlight.has(openKey)) {
      res.status(409).json({ error: 'Ouverture déjà en cours pour cette conversation' })
      return
    }
    opensInFlight.add(openKey)
  }
  try {
    await handleChat(req, res)
  } catch (e) {
    // Dernier filet (ne devrait pas arriver : handleChat gère ses erreurs).
    const message = e instanceof Error ? e.message : String(e)
    if (!res.headersSent) {
      res.status(500).json({ error: message })
    } else {
      try {
        writeEvent(res, { type: 'error', message })
        res.end()
      } catch {
        /* connexion fermée */
      }
    }
  } finally {
    if (openKey !== null) opensInFlight.delete(openKey)
  }
})

// ── Compaction ─────────────────────────────────────────────────────────────
// Même mécanique que le /compact de Claude Code : passe mémoire PUIS résumé, qui
// remplace les messages couverts dans les prochains payloads. La passe mémoire
// utilise les outils en mode complet ; en mode simple, c'est le serveur qui écrit
// (le modèle se contente de lister des faits en texte).

const COMPACT_MIN_MESSAGES = 6
// Six et non quatre : la passe mémoire sous garde-fou coûte un aller-retour de
// lecture par fichier existant touché (memory_read puis memory_update/append).
const COMPACT_MAX_ITERATIONS = 6
// Garde-fou d'horloge d'une compaction : au-delà, l'appel backend est abandonné
// et le verrou compactionsInFlight se libère (10 min — large, jamais infini).
const COMPACT_TIMEOUT_MS = 10 * 60_000
const COMPACT_KEEP_RECENT = 4 // messages récents laissés « vivants » après compaction
const COMPACT_SUMMARY_MAX_CHARS = 20000 // un résumé est un résumé, pas une archive

// ── Mode simple : la mémoire est écrite par le SERVEUR ─────────────────────
// Le petit modèle n'a aucun outil : on lui demande une simple liste de faits,
// en texte, et c'est Hanami qui la range dans le fichier mémoire.
const FACTS_DIRECTIVE =
  'List the important durable facts from this conversation worth remembering long-term, one per line, ' +
  'each line starting with "FACT: " — nothing else.'
const AUTO_MEMORY_FILE = 'auto-memory.md'
const AUTO_MEMORY_INDEX_LINE = `- [Remembered facts](${AUTO_MEMORY_FILE}) — facts extracted automatically during compaction`
const AUTO_MEMORY_MAX_FACTS = 20 // garde-fou : un modèle bavard ne noie pas la mémoire
const AUTO_MEMORY_MAX_CHARS = 500 // par fait

// Puce et gras optionnels autour du marqueur : les petits modèles écrivent
// volontiers « - **FACT:** … » malgré la consigne.
const FACT_LINE = /^[\s>*_-]*FACT[\s*_]*:[\s*_]*(.+)$/i

/** Faits extraits d'une réponse en texte libre (liste vide si le modèle n'a rien suivi). */
function parseFacts(text: string): string[] {
  const facts: string[] = []
  for (const line of text.split('\n')) {
    const m = FACT_LINE.exec(line)
    if (!m) continue
    const fact = m[1].replace(/[*_\s]+$/, '').trim()
    if (fact) facts.push(fact.slice(0, AUTO_MEMORY_MAX_CHARS))
    if (facts.length >= AUTO_MEMORY_MAX_FACTS) break
  }
  return facts
}

/** Ajoute les faits datés au fichier mémoire auto + tient l'index MEMORY.md à jour. */
function appendAutoFacts(charId: string, facts: string[]): void {
  const date = new Date().toISOString().slice(0, 10)
  const existing =
    readMemoryFile(charId, AUTO_MEMORY_FILE) ??
    '# Remembered facts\n\nExtracted automatically from conversations during compaction (simple mode).\n'
  const lines = facts.map((f) => `- **${date}** — ${f}`).join('\n')
  writeMemoryFile(charId, AUTO_MEMORY_FILE, existing.replace(/\n*$/, '\n') + '\n' + lines + '\n')
  // Upsert de la ligne d'index. index === null : MEMORY.md illisible — on
  // n'écrit PAS un index neuf par-dessus un fichier peut-être existant.
  const index = readMemoryFile(charId, 'MEMORY.md')
  if (index !== null && !index.includes(`](${AUTO_MEMORY_FILE})`)) {
    writeMemoryFile(charId, 'MEMORY.md', index.replace(/\n*$/, '\n') + AUTO_MEMORY_INDEX_LINE + '\n')
  }
}

// Verrou par chat : jamais deux compactions concurrentes sur le même fichier.
const compactionsInFlight = new Set<string>()

// memoryTools : la consigne « sers-toi des outils mémoire » n'a de sens que si
// des outils sont réellement exposés (jamais en mode simple).
function compactDirective(hasPrevSummary: boolean, memoryTools: boolean, instruction: string): string {
  let d =
    '[HANAMI COMPACTION]\n' +
    'The conversation above is about to be condensed to free up context. Write ONE summary that will ' +
    'replace these messages in your future context.\n' +
    '- Write the summary in the same language as the conversation.\n' +
    '- Preserve: key events, facts learned, decisions, promises, emotional beats, running jokes, and the current situation.\n'
  if (hasPrevSummary) {
    d +=
      '- A previous conversation summary is already in your system context: merge it with the new messages into one coherent, updated summary.\n'
  }
  if (memoryTools) {
    d +=
      '- BEFORE writing the summary, persist any durable facts worth remembering beyond this conversation: ' +
      'memory_read an existing memory file before memory_update (complete merged content), ' +
      'memory_append a fact to an existing file, memory_save only brand-new topics.\n'
  }
  if (instruction) d += `- User instruction for this compaction: ${instruction}\n`
  d += 'Reply with ONLY the summary text (no preamble, no emotion tag).'
  return d
}

async function runCompaction(
  characterId: string,
  chatId: string,
  instruction: string,
): Promise<{ summary: string; summaryUpto: number; compacted: number }> {
  const settings = loadSettings()
  const character = getCharacter(characterId)
  if (!character) throw new Error(`Personnage introuvable : ${characterId}`)
  const { meta, messages: history } = readChat(characterId, chatId)
  const prevUpto = meta.summary ? Math.min(meta.summaryUpto ?? 0, history.length) : 0
  const candidates = history.slice(prevUpto)
  if (candidates.length < COMPACT_MIN_MESSAGES) {
    throw new Error(`Rien à compacter (moins de ${COMPACT_MIN_MESSAGES} messages depuis le dernier résumé)`)
  }

  // Mode simple : pas de passe agentique, donc rien à annoncer sur les outils mémoire.
  const simple = settings.modelMode === 'simple'
  const names = macroNamesFor(character.name, settings)
  let systemText = character.systemPrompt
  if (settings.memoryEnabled) systemText += buildMemoryBlock(characterId, simple)
  if (meta.summary) systemText += summaryBlock(meta.summary)
  const directive = compactDirective(!!meta.summary, settings.memoryEnabled && !simple, instruction)

  // Prompt + complétion doivent tenir dans la fenêtre du modèle : les backends
  // stricts (vLLM, OpenAI…) rejettent sinon, et les permissifs (KoboldCpp)
  // tronqueraient par l'avant SANS erreur — résumé partiel, contexte perdu.
  const window = settings.contextSize > 0 ? settings.contextSize : 32768
  // Budget de sortie généreux (modèles « thinking ») mais jamais plus du tiers
  // de la fenêtre.
  const completionBudget = Math.min(Math.max(settings.maxTokens, 8192), Math.max(1024, Math.floor(window / 3)))
  let promptBudget =
    window - completionBudget - estimateTokens(systemText) - estimateTokens(directive) - 512 // marge outils

  // La tranche compactée part du plus ANCIEN et s'arrête au budget — les
  // messages récents restent vivants (continuité immédiate, comme /compact).
  // summaryUpto ne couvre QUE ce qui a réellement été soumis au modèle.
  const maxTake = Math.max(0, candidates.length - COMPACT_KEEP_RECENT)
  let take = 0
  while (take < maxTake) {
    const cost = estimateTokens(candidates[take])
    if (cost > promptBudget) break
    promptBudget -= cost
    take++
  }
  if (take < 1) {
    throw new Error('Fenêtre trop petite pour compacter — augmentez « Taille de contexte du modèle »')
  }
  const slice = candidates.slice(0, take)
  const upto = prevUpto + take

  // Mêmes macros que le chat : le modèle qui résume lit le personnage sous son
  // nom, pas sous « {{char}} ».
  const baseMessages: unknown[] = [
    { role: 'system', content: substituteMacros(systemText, names) },
    ...slice.map((m) => ({ role: m.role, content: substituteMacros(m.content, names) })),
  ]
  const messages: unknown[] = [...baseMessages, { role: 'user', content: directive }]
  const tools = settings.memoryEnabled && !simple ? memoryToolDefs : []
  const abort = new AbortController()
  // Garde-fou d'horloge : sans lui, un backend qui ne répond jamais laissait le
  // verrou compactionsInFlight posé pour toute la vie du processus (l'appelant
  // ne peut pas annuler — le résumé doit persister même si le client est parti,
  // choix assumé). Large : une compaction est lente par nature. Pas de clear :
  // aborter un stream déjà terminé est un no-op, et unref n'empêche pas l'arrêt.
  const timer = setTimeout(() => abort.abort(), COMPACT_TIMEOUT_MS)
  timer.unref()
  const compactSettings: Settings = { ...settings, maxTokens: completionBudget }

  let summary = ''
  let lastFinish = ''
  // Faits collectés en mode simple — écrits UNIQUEMENT après un résumé réussi :
  // si la compaction échoue puis est relancée, les mêmes faits repasseraient et
  // se dupliqueraient dans le fichier mémoire.
  let pendingFacts: string[] = []

  if (simple) {
    // (a) Passe mémoire SANS outils : le modèle liste des faits, le serveur les
    // range. Une réponse hors format ne donne aucun fait — on continue sans bruit.
    if (settings.memoryEnabled) {
      try {
        const factsResult = await streamChatCompletion({
          settings: compactSettings,
          messages: [...baseMessages, { role: 'user', content: FACTS_DIRECTIVE }],
          signal: abort.signal,
          onDelta: () => {},
        })
        pendingFacts = parseFacts(factsResult.content)
      } catch (e) {
        // La mémoire est un bonus : l'échec ne doit pas emporter le résumé
        // (si le backend est vraiment tombé, l'appel suivant le dira).
        console.warn('[compact:facts]', e instanceof Error ? e.message : String(e))
      }
    }
    // (b) Résumé, toujours sans outils.
    const result = await streamChatCompletion({
      settings: compactSettings,
      messages,
      signal: abort.signal,
      onDelta: () => {},
    })
    lastFinish = result.finishReason
    summary = result.content.trim()
  } else {
    // Boucle agentique silencieuse (partagée avec le chat, cf. runToolLoop) :
    // le résumé = le texte du DERNIER appel — celui sans appels d'outils, ou le
    // dernier forcé sans outils quand le budget est épuisé.
    const mem = createMemorySession() // lectures mémoire de CETTE compaction (garde-fou)
    const { last } = await runToolLoop(
      characterId,
      settings,
      messages,
      COMPACT_MAX_ITERATIONS,
      toolNamesOf(tools),
      mem,
      async (withTools) => {
        const result = await streamChatCompletion({
          settings: compactSettings,
          messages,
          tools: withTools && tools.length > 0 ? tools : undefined,
          signal: abort.signal,
          onDelta: () => {},
        })
        lastFinish = result.finishReason
        return result
      },
    )
    summary = last.content.trim()
  }
  if (!summary) {
    throw new Error(
      `Le modèle n'a pas produit de résumé (fin de génération : ${lastFinish || 'inconnue'} — ` +
        `pensez à augmenter « Tokens max » ou la fenêtre du backend)`,
    )
  }
  summary = summary.slice(0, COMPACT_SUMMARY_MAX_CHARS)

  // Le résumé a réussi : les faits du mode simple peuvent être rangés sans
  // risque de doublon au prochain essai.
  if (pendingFacts.length > 0) appendAutoFacts(characterId, pendingFacts)

  updateChatHeader(characterId, chatId, { summary, summaryUpto: upto })
  return { summary, summaryUpto: upto, compacted: upto - prevUpto }
}

// POST /api/chat/compact {characterId, chatId, instruction?} — compaction manuelle ou auto.
chatRouter.post('/api/chat/compact', async (req, res) => {
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; instruction?: unknown }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const instruction = typeof body.instruction === 'string' ? body.instruction.trim().slice(0, 2000) : ''
  if (!characterId || !chatId) {
    res.status(400).json({ error: 'characterId et chatId sont requis' })
    return
  }
  try {
    readChat(characterId, chatId)
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  const lockKey = `${characterId}/${chatId}`
  if (compactionsInFlight.has(lockKey)) {
    res.status(409).json({ error: 'Compaction déjà en cours pour cette conversation' })
    return
  }
  compactionsInFlight.add(lockKey)
  try {
    res.json(await runCompaction(characterId, chatId, instruction))
  } catch (e) {
    res.status(500).json({ error: e instanceof Error ? e.message : String(e) })
  } finally {
    compactionsInFlight.delete(lockKey)
  }
})

// PUT /api/chat/message {characterId, chatId, index, content} — édition d'un message
// en place (l'émotion est re-détectée pour les messages de l'assistant).
//
// Une réponse à variantes édite CELLE QUI EST AFFICHÉE et perd les autres :
// écrire soi-même le texte est un choix définitif, on ne feuillette plus après.
chatRouter.put('/api/chat/message', (req, res) => {
  const body = (req.body ?? {}) as {
    characterId?: unknown
    chatId?: unknown
    index?: unknown
    content?: unknown
  }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const index = typeof body.index === 'number' && Number.isInteger(body.index) ? body.index : -1
  const content = typeof body.content === 'string' ? body.content : ''
  if (!characterId || !chatId || index < 0 || !content.trim()) {
    res.status(400).json({ error: 'characterId, chatId, index et content sont requis' })
    return
  }
  let count: number
  try {
    count = readChat(characterId, chatId).messages.length
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  if (index >= count) {
    res.status(404).json({ error: `Message introuvable : ${index}` })
    return
  }
  let updated: ChatMessage | null = null
  rewriteChatMessages(characterId, chatId, (msgs) => {
    const msg: ChatMessage = { ...pruneVariants(msgs[index]), content }
    if (msg.role === 'assistant') {
      delete msg.emotion
      const emotion = firstEmotionTag(content)
      if (emotion) msg.emotion = emotion
    }
    msgs[index] = msg
    updated = msg
    return msgs
  })
  res.json({ index, message: updated })
})

// PUT /api/chat/variant {characterId, chatId, index, variant} — change la variante
// AFFICHÉE d'une réponse (« swipe »). Le corps du message recopie la variante
// choisie : le payload du prochain envoi, l'export .md, la voix, la copie et
// l'émotion du visage la suivent aussitôt, sans rien savoir des variantes.
//
// AUCUN message n'est ajouté ni retiré : l'index reste celui du message, et les
// repères qui comptent des messages (épingle, summaryUpto) sont hors sujet ici.
chatRouter.put('/api/chat/variant', (req, res) => {
  const body = (req.body ?? {}) as {
    characterId?: unknown
    chatId?: unknown
    index?: unknown
    variant?: unknown
  }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const index = typeof body.index === 'number' && Number.isInteger(body.index) ? body.index : -1
  const variant = typeof body.variant === 'number' && Number.isInteger(body.variant) ? body.variant : -1
  if (!characterId || !chatId || index < 0 || variant < 0) {
    res.status(400).json({ error: 'characterId, chatId, index et variant (entiers ≥ 0) sont requis' })
    return
  }
  let messages: ChatMessage[]
  try {
    messages = readChat(characterId, chatId).messages
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  if (index >= messages.length) {
    res.status(404).json({ error: `Message introuvable : ${index}` })
    return
  }
  const target = messages[index]
  if (!target.variants || target.variants.length < 2) {
    res.status(400).json({ error: `Ce message n'a pas de variantes : ${index}` })
    return
  }
  if (variant >= target.variants.length) {
    res.status(404).json({ error: `Variante introuvable : ${variant}` })
    return
  }
  let updated: ChatMessage | null = null
  rewriteChatMessages(characterId, chatId, (msgs) => {
    const msg = msgs[index]
    // Le fil a pu bouger entre la lecture et la réécriture : sans variantes (ou
    // moins nombreuses), on ne touche à rien.
    if (!msg || !msg.variants || variant >= msg.variants.length) return msgs
    updated = withVariants(msg, msg.variants, variant)
    msgs[index] = updated
    return msgs
  })
  if (updated === null) {
    res.status(409).json({ error: 'La conversation a changé — variante introuvable' })
    return
  }
  res.json({ index, message: updated })
})

// DELETE /api/chat/message {characterId, chatId, index} — retire UN message du fil.
// Le pendant de l'édition : « Régénérer » ne sait défaire que la dernière réponse,
// une bulle ratée au milieu du fil n'avait aucune sortie.
//
// Les deux repères de l'en-tête qui comptent des messages doivent suivre le
// décalage, sans quoi le prochain envoi partirait de travers :
//   · `pinned` — l'ordinal épinglé (le message supprimé perd son épingle) ;
//   · `summaryUpto` — la frontière du résumé de compaction, qui décide de la
//     tranche d'historique envoyée au modèle.
chatRouter.delete('/api/chat/message', (req, res) => {
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; index?: unknown }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const index = typeof body.index === 'number' && Number.isInteger(body.index) ? body.index : -1
  if (!characterId || !chatId || index < 0) {
    res.status(400).json({ error: 'characterId, chatId et index sont requis' })
    return
  }
  let meta
  try {
    meta = readChat(characterId, chatId).meta
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  if (index >= meta.messageCount) {
    res.status(404).json({ error: `Message introuvable : ${index}` })
    return
  }
  rewriteChatMessages(characterId, chatId, (msgs) => msgs.filter((_, i) => i !== index))
  // Épingle et frontière de résumé recalées sur le fil raccourci.
  const pinned =
    typeof meta.pinned !== 'number' ? undefined : meta.pinned === index ? undefined : meta.pinned > index ? meta.pinned - 1 : meta.pinned
  const summaryUpto =
    meta.summary && typeof meta.summaryUpto === 'number' && meta.summaryUpto > index
      ? meta.summaryUpto - 1
      : meta.summaryUpto
  if (pinned !== meta.pinned || summaryUpto !== meta.summaryUpto) {
    updateChatHeader(characterId, chatId, {
      pinned,
      ...(meta.summary ? { summaryUpto } : {}),
    })
  }
  res.json({ index, messageCount: meta.messageCount - 1, pinned: pinned ?? null })
})

// PUT /api/chat/summary {characterId, chatId, summary} — édition (ou retrait) du résumé.
chatRouter.put('/api/chat/summary', (req, res) => {
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; summary?: unknown }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const summary = typeof body.summary === 'string' ? body.summary : null
  if (!characterId || !chatId || summary === null) {
    res.status(400).json({ error: 'characterId, chatId et summary sont requis' })
    return
  }
  let meta
  try {
    meta = readChat(characterId, chatId).meta
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  if (!meta.summary) {
    res.status(400).json({ error: "Ce chat n'a pas encore de résumé de compaction" })
    return
  }
  // Résumé vidé = compaction annulée : l'historique complet repart dans le payload.
  if (summary.trim() === '') {
    updateChatHeader(characterId, chatId, { summary: undefined, summaryUpto: undefined })
    res.json({ summary: '', summaryUpto: 0 })
    return
  }
  const capped = summary.slice(0, COMPACT_SUMMARY_MAX_CHARS)
  updateChatHeader(characterId, chatId, { summary: capped, summaryUpto: meta.summaryUpto ?? 0 })
  res.json({ summary: capped, summaryUpto: meta.summaryUpto ?? 0 })
})

// PUT /api/chat/scene {characterId, chatId, sceneNotes} — notes de scène de la
// conversation (vider = retirer le bloc du system prompt). Le champ vit dans
// l'en-tête du .jsonl : la compaction, qui ne patche que summary/summaryUpto, n'y touche pas.
chatRouter.put('/api/chat/scene', (req, res) => {
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; sceneNotes?: unknown }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const sceneNotes = typeof body.sceneNotes === 'string' ? body.sceneNotes : null
  if (!characterId || !chatId || sceneNotes === null) {
    res.status(400).json({ error: 'characterId, chatId et sceneNotes sont requis' })
    return
  }
  try {
    readChat(characterId, chatId)
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  // Notes vidées : la clé disparaît de l'en-tête, donc plus aucun bloc injecté.
  const capped = sceneNotes.trim() ? sceneNotes.slice(0, SCENE_NOTES_MAX_CHARS) : ''
  updateChatHeader(characterId, chatId, { sceneNotes: capped || undefined })
  res.json({ sceneNotes: capped })
})

// PUT /api/chat/pin {characterId, chatId, pinned} — épingle un message (ordinal =
// position dans le fichier) ou le désépingle (null). Gadget PUREMENT visuel : le
// message épinglé ne pèse rien dans buildPayload, il ne fait que voyager dans
// l'en-tête du .jsonl et remonter avec le meta du chat.
chatRouter.put('/api/chat/pin', (req, res) => {
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; pinned?: unknown }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  // undefined = champ absent ou mal typé (400) ; null = désépingler.
  const pinned =
    body.pinned === null
      ? null
      : typeof body.pinned === 'number' && Number.isInteger(body.pinned) && body.pinned >= 0
        ? body.pinned
        : undefined
  if (!characterId || !chatId || pinned === undefined) {
    res.status(400).json({ error: 'characterId, chatId et pinned (entier ≥ 0 ou null) sont requis' })
    return
  }
  let count: number
  try {
    count = readChat(characterId, chatId).messages.length
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  if (pinned !== null && pinned >= count) {
    res.status(404).json({ error: `Message introuvable : ${pinned}` })
    return
  }
  updateChatHeader(characterId, chatId, { pinned: pinned ?? undefined })
  res.json({ pinned })
})

// GET /api/prompt-preview?characterId=&chatId= — MÊME code que POST /api/chat (buildPayload).
chatRouter.get('/api/prompt-preview', (req, res) => {
  const characterId = typeof req.query.characterId === 'string' ? req.query.characterId : ''
  const chatId = typeof req.query.chatId === 'string' ? req.query.chatId : ''
  if (!characterId || !chatId) {
    res.status(400).json({ error: 'characterId et chatId sont requis' })
    return
  }
  try {
    const settings = loadSettings()
    const { systemText, characterPrompt, injected, payload } = buildPayload(characterId, chatId, settings)
    res.json({
      systemText,
      // Les deux morceaux du texte système, pour que l'inspecteur puisse rendre
      // le prompt du personnage éditable et laisser le reste en lecture seule.
      characterPrompt,
      injected,
      payload,
      // Jauge de contexte : estimation du prochain envoi + fenêtre de travail
      // (plafonnée, cf. workingWindow) — MÊME limite que l'événement « done » du
      // chat, sinon la jauge sauterait à l'ouverture d'une conversation. Les
      // définitions d'outils partent aussi dans le payload (et l'usage réel du
      // backend les compte) : sans elles, elle sautait au premier message.
      tokens: estimateTokens(payload.messages) + estimateTokens(payload.tools ?? []),
      contextSize: workingWindow(settings),
    })
  } catch (e) {
    res.status(404).json({ error: e instanceof Error ? e.message : String(e) })
  }
})
