// POST /api/chat — boucle agentique + streaming SSE — et GET /api/prompt-preview.
// TRANSPARENCE TOTALE : le payload envoyé au backend = system prompt du personnage
// + bloc mémoire (si actif) + historique + message user. RIEN d'autre n'est injecté.
// buildPayload est LA source unique, partagée avec /api/prompt-preview.
import { Router } from 'express'
import type { Request, Response } from 'express'
import { loadSettings } from '../config'
import { appendChatMessage, buildMemoryBlock, getCharacter, readChat, updateChatHeader } from '../lib/storage'
import { streamChatCompletion } from '../llm/openai'
import { MEMORY_TOOL_NAMES, executeMemoryTool, memoryToolDefs } from '../tools/memoryTools'
import { FILE_TOOL_NAMES, executeFileTool, fileToolDefs } from '../tools/fileTools'
import type { ChatEvent, ChatMessage, ContextInfo, Settings } from '../../shared/types'

export const chatRouter = Router()

const MAX_TOOL_ITERATIONS = 6
// Non ancrée : première occurrence n'importe où, comme extractEmotion côté client.
// \s* : les modèles écrivent parfois « [ happy ] » avec des espaces.
const EMOTION_RE = /\[\s*(neutral|happy|sad|angry|surprised|relaxed)\s*\]/i

interface BackendPayload {
  messages: unknown[]
  tools?: unknown[]
  model: string
  temperature: number
  max_tokens: number
}

/** Bloc résumé de compaction injecté dans le system prompt (visible dans l'inspecteur). */
function summaryBlock(summary: string): string {
  return `\n\n## Conversation summary (auto-generated by Hanami compaction — earlier messages were condensed into this)\n\n${summary}`
}

/** Estimation grossière du volume de tokens (~4 caractères/token sur le JSON). */
function estimateTokens(value: unknown): number {
  return Math.ceil(JSON.stringify(value).length / 4)
}

/** Écart humanisé entre deux messages (en anglais : langue de travail des prompts). */
function humanizeGap(ms: number): string {
  const min = Math.floor(ms / 60000)
  if (min < 1) return 'less than a minute'
  if (min < 60) return `${min} minute${min > 1 ? 's' : ''}`
  const h = Math.floor(min / 60)
  if (h < 48) return `${h} hour${h > 1 ? 's' : ''}`
  return `${Math.floor(h / 24)} days`
}

// Bloc temporel : le personnage sait QUAND on lui parle (matin/soir, retour
// après des jours…). Faits bruts en anglais — le modèle les exprime dans la
// langue de la conversation. Visible dans l'inspecteur comme tout le reste.
const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

function timeBlock(lastMessageTs: string | null): string {
  const now = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  let block =
    '\n\n## Current time (auto-injected by Hanami)\n' +
    `Now: ${WEEKDAYS[now.getDay()]} ${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}, ` +
    `${pad(now.getHours())}:${pad(now.getMinutes())} (user's local time).\n`
  if (lastMessageTs) {
    const gap = now.getTime() - new Date(lastMessageTs).getTime()
    if (Number.isFinite(gap) && gap >= 0) {
      block += `Time since the previous message in this conversation: ${humanizeGap(gap)}.\n`
    }
  }
  block += 'Let this inform your replies naturally (greetings, time of day, absences) — never recite it.\n'
  return block
}

/** Construit le payload EXACT envoyé au backend (aussi renvoyé tel quel par /api/prompt-preview). */
function buildPayload(
  characterId: string,
  chatId: string,
  settings: Settings,
  pendingUserContent?: string,
): { systemText: string; payload: BackendPayload } {
  const character = getCharacter(characterId)
  if (!character) throw new Error(`Personnage introuvable : ${characterId}`)
  let systemText = character.systemPrompt
  if (settings.memoryEnabled) systemText += buildMemoryBlock(characterId)

  const { meta, messages: history } = readChat(characterId, chatId)
  // Conversation compactée : le résumé (dans le system) remplace les messages qu'il couvre.
  const upto = meta.summary ? Math.min(meta.summaryUpto ?? 0, history.length) : 0
  if (meta.summary) systemText += summaryBlock(meta.summary)
  if (settings.timeAwareness) {
    systemText += timeBlock(history.length > 0 ? history[history.length - 1].ts : null)
  }
  const live = history.slice(upto)
  const recent = settings.maxHistoryMessages > 0 ? live.slice(-settings.maxHistoryMessages) : []
  const messages: unknown[] = [
    { role: 'system', content: systemText },
    ...recent.map((m) => ({ role: m.role, content: m.content })),
  ]
  if (pendingUserContent !== undefined) messages.push({ role: 'user', content: pendingUserContent })

  const tools: unknown[] = [
    ...(settings.memoryEnabled ? memoryToolDefs : []),
    ...(settings.fileToolsEnabled ? fileToolDefs : []),
  ]
  const payload: BackendPayload = {
    messages,
    model: settings.model,
    temperature: settings.temperature,
    max_tokens: settings.maxTokens,
  }
  if (tools.length > 0) payload.tools = tools
  return { systemText, payload }
}

function toAssistantMessage(text: string, thinking?: string): ChatMessage {
  const m = EMOTION_RE.exec(text)
  const msg: ChatMessage = { role: 'assistant', content: text, ts: new Date().toISOString() }
  if (m) msg.emotion = m[1].toLowerCase()
  if (thinking) msg.thinking = thinking
  return msg
}

/** Registre des outils : route l'appel vers mémoire ou fichiers. */
function executeTool(characterId: string, settings: Settings, name: string, rawArgs: string): string {
  let args: Record<string, unknown>
  try {
    args = rawArgs.trim() ? (JSON.parse(rawArgs) as Record<string, unknown>) : {}
  } catch {
    throw new Error(`arguments JSON invalides pour ${name}`)
  }
  if ((MEMORY_TOOL_NAMES as readonly string[]).includes(name)) {
    return executeMemoryTool(characterId, name, args)
  }
  if ((FILE_TOOL_NAMES as readonly string[]).includes(name)) {
    return executeFileTool(settings, name, args)
  }
  throw new Error(`Outil inconnu : ${name}`)
}

function writeEvent(res: Response, ev: ChatEvent): void {
  res.write('data: ' + JSON.stringify(ev) + '\n\n')
}

async function handleChat(req: Request, res: Response): Promise<void> {
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; content?: unknown }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const content = typeof body.content === 'string' ? body.content : ''
  if (!characterId || !chatId || !content) {
    res.status(400).json({ error: 'characterId, chatId et content sont requis' })
    return
  }
  const settings = loadSettings()
  if (!getCharacter(characterId)) {
    res.status(404).json({ error: `Personnage introuvable : ${characterId}` })
    return
  }
  try {
    readChat(characterId, chatId)
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }

  // Payload construit AVANT la sauvegarde : le message courant passe par pendingUserContent,
  // sinon il consommerait un slot d'historique (et ne serait jamais envoyé si
  // maxHistoryMessages = 0).
  const { payload } = buildPayload(characterId, chatId, settings, content)
  const messages = payload.messages as Record<string, unknown>[]

  // Le message user est sauvegardé AVANT l'appel backend : il survit à toute erreur en aval.
  appendChatMessage(characterId, chatId, { role: 'user', content, ts: new Date().toISOString() })

  res.setHeader('Content-Type', 'text/event-stream')
  res.setHeader('Cache-Control', 'no-cache')
  res.setHeader('Connection', 'keep-alive')
  res.flushHeaders()

  const abort = new AbortController()
  // Déconnexion client en plein stream → on coupe l'appel backend.
  // res 'close' + writableEnded, car req 'close' se déclenche dès la fin du body en Node ≥ 15.
  res.on('close', () => {
    if (!res.writableEnded) abort.abort()
  })

  let assistantText = ''
  let assistantThinking = ''

  // Un appel streaming. Entre deux itérations, un séparateur "\n\n" est inséré dans le texte
  // ET émis comme delta : le flux affiché et le texte sauvegardé restent identiques.
  const streamOnce = (withTools: boolean) => {
    let firstDelta = true
    let firstThinking = true
    return streamChatCompletion({
      settings,
      messages,
      tools: withTools ? payload.tools : undefined,
      signal: abort.signal,
      onDelta: (text) => {
        if (firstDelta) {
          firstDelta = false
          if (assistantText.length > 0) {
            assistantText += '\n\n'
            writeEvent(res, { type: 'delta', text: '\n\n' })
          }
        }
        assistantText += text
        writeEvent(res, { type: 'delta', text })
      },
      onThinking: (text) => {
        if (firstThinking) {
          firstThinking = false
          if (assistantThinking.length > 0) assistantThinking += '\n\n'
        }
        assistantThinking += text
        writeEvent(res, { type: 'thinking', text })
      },
    })
  }

  try {
    let truncated = false
    let finishReason = ''
    let pendingTools = false
    let promptTokens = 0

    for (let iteration = 0; iteration < MAX_TOOL_ITERATIONS; iteration++) {
      const result = await streamOnce(true)
      truncated = result.truncated
      finishReason = result.finishReason
      if (result.promptTokens > 0) promptTokens = result.promptTokens
      if (result.toolCalls.length === 0) {
        pendingTools = false
        break
      }
      pendingTools = true

      // Trace fidèle de l'aller-retour outil dans le contexte de la boucle.
      messages.push({
        role: 'assistant',
        content: result.content || null,
        tool_calls: result.toolCalls.map((tc) => ({
          id: tc.id,
          type: 'function',
          function: { name: tc.name, arguments: tc.arguments },
        })),
      })
      for (const tc of result.toolCalls) {
        let toolResult: string
        try {
          toolResult = executeTool(characterId, settings, tc.name, tc.arguments)
        } catch (e) {
          toolResult = `Erreur : ${e instanceof Error ? e.message : String(e)}`
        }
        writeEvent(res, { type: 'tool', name: tc.name, args: tc.arguments, result: toolResult })
        messages.push({ role: 'tool', tool_call_id: tc.id, content: toolResult })
      }
    }

    if (pendingTools) {
      // Budget d'itérations épuisé alors que le modèle demande encore des outils :
      // un dernier appel SANS outils pour obtenir la réponse finale.
      const result = await streamOnce(false)
      truncated = result.truncated
      finishReason = result.finishReason
      if (result.promptTokens > 0) promptTokens = result.promptTokens
      if (assistantText.length === 0) {
        // Rien à sauvegarder : pas de message vide, pas de done.
        writeEvent(res, { type: 'error', message: "Budget d'outils épuisé sans réponse du modèle" })
        res.end()
        return
      }
    }

    // Contenu INTÉGRAL, tel que généré (le tag d'émotion reste dans le texte).
    const message = toAssistantMessage(assistantText, assistantThinking)
    appendChatMessage(characterId, chatId, message)
    // Jauge de contexte : usage réel du backend quand il le fournit, sinon
    // estimation sur le payload final (qui inclut les allers-retours d'outils).
    const tokens =
      (promptTokens > 0 ? promptTokens : estimateTokens(messages)) + estimateTokens(assistantText)
    const context: ContextInfo = {
      tokens,
      limit: settings.contextSize,
      percent: settings.contextSize > 0 ? Math.min(100, Math.round((tokens / settings.contextSize) * 100)) : 0,
    }
    writeEvent(res, { type: 'done', message, context })
    // Signalé APRÈS la sauvegarde et le done : le client affiche la bulle d'erreur discrète.
    if (truncated || finishReason === 'length') {
      writeEvent(res, {
        type: 'error',
        message: truncated
          ? 'Réponse probablement tronquée (flux interrompu avant la fin)'
          : 'Réponse coupée (max_tokens atteint)',
      })
    }
    res.end()
  } catch (e) {
    if (abort.signal.aborted) {
      // Client parti : on sauvegarde le partiel si au moins un delta est arrivé.
      if (assistantText.length > 0) {
        appendChatMessage(characterId, chatId, toAssistantMessage(assistantText, assistantThinking))
      }
      try {
        res.end()
      } catch {
        /* socket déjà fermée */
      }
      return
    }
    const message = e instanceof Error ? e.message : String(e)
    if (assistantText.length > 0) {
      // Erreur mi-flux : le partiel déjà affiché côté client est sauvegardé, et joint à l'événement.
      const partial = toAssistantMessage(assistantText, assistantThinking)
      appendChatMessage(characterId, chatId, partial)
      writeEvent(res, { type: 'error', message, partial })
    } else {
      writeEvent(res, { type: 'error', message })
    }
    res.end()
  }
}

chatRouter.post('/api/chat', async (req, res) => {
  try {
    await handleChat(req, res)
  } catch (e) {
    // Dernier filet (ne devrait pas arriver : handleChat gère ses erreurs).
    const message = e instanceof Error ? e.message : String(e)
    if (!res.headersSent) {
      res.status(500).json({ error: message })
    } else {
      try {
        writeEvent(res, { type: 'error', message })
        res.end()
      } catch {
        /* connexion fermée */
      }
    }
  }
})

// ── Compaction ─────────────────────────────────────────────────────────────
// Même mécanique que le /compact de Claude Code : passe mémoire (outils) PUIS
// résumé, qui remplace les messages couverts dans les prochains payloads.

const COMPACT_MIN_MESSAGES = 6
const COMPACT_MAX_ITERATIONS = 4
const COMPACT_KEEP_RECENT = 4 // messages récents laissés « vivants » après compaction
const COMPACT_SUMMARY_MAX_CHARS = 20000 // un résumé est un résumé, pas une archive

// Verrou par chat : jamais deux compactions concurrentes sur le même fichier.
const compactionsInFlight = new Set<string>()

function compactDirective(hasPrevSummary: boolean, memoryEnabled: boolean, instruction: string): string {
  let d =
    '[HANAMI COMPACTION]\n' +
    'The conversation above is about to be condensed to free up context. Write ONE summary that will ' +
    'replace these messages in your future context.\n' +
    '- Write the summary in the same language as the conversation.\n' +
    '- Preserve: key events, facts learned, decisions, promises, emotional beats, running jokes, and the current situation.\n'
  if (hasPrevSummary) {
    d +=
      '- A previous conversation summary is already in your system context: merge it with the new messages into one coherent, updated summary.\n'
  }
  if (memoryEnabled) {
    d +=
      '- BEFORE writing the summary, use the memory tools (memory_save / memory_update) to persist any durable facts worth remembering beyond this conversation.\n'
  }
  if (instruction) d += `- User instruction for this compaction: ${instruction}\n`
  d += 'Reply with ONLY the summary text (no preamble, no emotion tag).'
  return d
}

async function runCompaction(
  characterId: string,
  chatId: string,
  instruction: string,
): Promise<{ summary: string; summaryUpto: number; compacted: number }> {
  const settings = loadSettings()
  const character = getCharacter(characterId)
  if (!character) throw new Error(`Personnage introuvable : ${characterId}`)
  const { meta, messages: history } = readChat(characterId, chatId)
  const prevUpto = meta.summary ? Math.min(meta.summaryUpto ?? 0, history.length) : 0
  const candidates = history.slice(prevUpto)
  if (candidates.length < COMPACT_MIN_MESSAGES) {
    throw new Error(`Rien à compacter (moins de ${COMPACT_MIN_MESSAGES} messages depuis le dernier résumé)`)
  }

  let systemText = character.systemPrompt
  if (settings.memoryEnabled) systemText += buildMemoryBlock(characterId)
  if (meta.summary) systemText += summaryBlock(meta.summary)
  const directive = compactDirective(!!meta.summary, settings.memoryEnabled, instruction)

  // Prompt + complétion doivent tenir dans la fenêtre du modèle : les backends
  // stricts (vLLM, OpenAI…) rejettent sinon, et les permissifs (KoboldCpp)
  // tronqueraient par l'avant SANS erreur — résumé partiel, contexte perdu.
  const window = settings.contextSize > 0 ? settings.contextSize : 32768
  // Budget de sortie généreux (modèles « thinking ») mais jamais plus du tiers
  // de la fenêtre.
  const completionBudget = Math.min(Math.max(settings.maxTokens, 8192), Math.max(1024, Math.floor(window / 3)))
  let promptBudget =
    window - completionBudget - estimateTokens(systemText) - estimateTokens(directive) - 512 // marge outils

  // La tranche compactée part du plus ANCIEN et s'arrête au budget — les
  // messages récents restent vivants (continuité immédiate, comme /compact).
  // summaryUpto ne couvre QUE ce qui a réellement été soumis au modèle.
  const maxTake = Math.max(0, candidates.length - COMPACT_KEEP_RECENT)
  let take = 0
  while (take < maxTake) {
    const cost = estimateTokens(candidates[take])
    if (cost > promptBudget) break
    promptBudget -= cost
    take++
  }
  if (take < 1) {
    throw new Error('Fenêtre trop petite pour compacter — augmentez « Taille de contexte du modèle »')
  }
  const slice = candidates.slice(0, take)
  const upto = prevUpto + take

  const messages: unknown[] = [
    { role: 'system', content: systemText },
    ...slice.map((m) => ({ role: m.role, content: m.content })),
    { role: 'user', content: directive },
  ]
  const tools = settings.memoryEnabled ? memoryToolDefs : []
  const abort = new AbortController()
  const compactSettings: Settings = { ...settings, maxTokens: completionBudget }

  // Boucle agentique silencieuse : le résumé = le texte du DERNIER appel
  // (les textes intermédiaires accompagnant des appels d'outils sont ignorés).
  let summary = ''
  let pendingTools = false
  let lastFinish = ''
  for (let iteration = 0; iteration < COMPACT_MAX_ITERATIONS; iteration++) {
    const result = await streamChatCompletion({
      settings: compactSettings,
      messages,
      tools: tools.length > 0 ? tools : undefined,
      signal: abort.signal,
      onDelta: () => {},
    })
    lastFinish = result.finishReason
    if (result.toolCalls.length === 0) {
      summary = result.content.trim()
      pendingTools = false
      break
    }
    pendingTools = true
    messages.push({
      role: 'assistant',
      content: result.content || null,
      tool_calls: result.toolCalls.map((tc) => ({
        id: tc.id,
        type: 'function',
        function: { name: tc.name, arguments: tc.arguments },
      })),
    })
    for (const tc of result.toolCalls) {
      let toolResult: string
      try {
        toolResult = executeTool(characterId, settings, tc.name, tc.arguments)
      } catch (e) {
        toolResult = `Erreur : ${e instanceof Error ? e.message : String(e)}`
      }
      messages.push({ role: 'tool', tool_call_id: tc.id, content: toolResult })
    }
  }
  if (pendingTools) {
    // Budget épuisé : un dernier appel sans outils pour obtenir le résumé.
    const result = await streamChatCompletion({
      settings: compactSettings,
      messages,
      signal: abort.signal,
      onDelta: () => {},
    })
    lastFinish = result.finishReason
    summary = result.content.trim()
  }
  if (!summary) {
    throw new Error(
      `Le modèle n'a pas produit de résumé (fin de génération : ${lastFinish || 'inconnue'} — ` +
        `pensez à augmenter « Tokens max » ou la fenêtre du backend)`,
    )
  }
  summary = summary.slice(0, COMPACT_SUMMARY_MAX_CHARS)

  updateChatHeader(characterId, chatId, { summary, summaryUpto: upto })
  return { summary, summaryUpto: upto, compacted: upto - prevUpto }
}

// POST /api/chat/compact {characterId, chatId, instruction?} — compaction manuelle ou auto.
chatRouter.post('/api/chat/compact', async (req, res) => {
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; instruction?: unknown }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const instruction = typeof body.instruction === 'string' ? body.instruction.trim().slice(0, 2000) : ''
  if (!characterId || !chatId) {
    res.status(400).json({ error: 'characterId et chatId sont requis' })
    return
  }
  try {
    readChat(characterId, chatId)
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  const lockKey = `${characterId}/${chatId}`
  if (compactionsInFlight.has(lockKey)) {
    res.status(409).json({ error: 'Compaction déjà en cours pour cette conversation' })
    return
  }
  compactionsInFlight.add(lockKey)
  try {
    res.json(await runCompaction(characterId, chatId, instruction))
  } catch (e) {
    res.status(500).json({ error: e instanceof Error ? e.message : String(e) })
  } finally {
    compactionsInFlight.delete(lockKey)
  }
})

// PUT /api/chat/summary {characterId, chatId, summary} — édition (ou retrait) du résumé.
chatRouter.put('/api/chat/summary', (req, res) => {
  const body = (req.body ?? {}) as { characterId?: unknown; chatId?: unknown; summary?: unknown }
  const characterId = typeof body.characterId === 'string' ? body.characterId : ''
  const chatId = typeof body.chatId === 'string' ? body.chatId : ''
  const summary = typeof body.summary === 'string' ? body.summary : null
  if (!characterId || !chatId || summary === null) {
    res.status(400).json({ error: 'characterId, chatId et summary sont requis' })
    return
  }
  let meta
  try {
    meta = readChat(characterId, chatId).meta
  } catch {
    res.status(404).json({ error: `Chat introuvable : ${chatId}` })
    return
  }
  if (!meta.summary) {
    res.status(400).json({ error: "Ce chat n'a pas encore de résumé de compaction" })
    return
  }
  // Résumé vidé = compaction annulée : l'historique complet repart dans le payload.
  if (summary.trim() === '') {
    updateChatHeader(characterId, chatId, { summary: undefined, summaryUpto: undefined })
    res.json({ summary: '', summaryUpto: 0 })
    return
  }
  const capped = summary.slice(0, COMPACT_SUMMARY_MAX_CHARS)
  updateChatHeader(characterId, chatId, { summary: capped, summaryUpto: meta.summaryUpto ?? 0 })
  res.json({ summary: capped, summaryUpto: meta.summaryUpto ?? 0 })
})

// GET /api/prompt-preview?characterId=&chatId= — MÊME code que POST /api/chat (buildPayload).
chatRouter.get('/api/prompt-preview', (req, res) => {
  const characterId = typeof req.query.characterId === 'string' ? req.query.characterId : ''
  const chatId = typeof req.query.chatId === 'string' ? req.query.chatId : ''
  if (!characterId || !chatId) {
    res.status(400).json({ error: 'characterId et chatId sont requis' })
    return
  }
  try {
    const settings = loadSettings()
    const { systemText, payload } = buildPayload(characterId, chatId, settings)
    res.json({
      systemText,
      payload,
      // Jauge de contexte : estimation du prochain envoi + limite configurée.
      tokens: estimateTokens(payload.messages),
      contextSize: settings.contextSize,
    })
  } catch (e) {
    res.status(404).json({ error: e instanceof Error ? e.message : String(e) })
  }
})
